# Generated by Django 5.2.15 on 2026-06-25 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_orderitem'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField()),
                ('reorder_target', models.PositiveIntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=127)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_levels', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_levels', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_levels', to='tenants.tenant')),
            ],
            options={
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['tenant', 'store', 'is_active'], name='cat_inv_tnt_store_active'), models.Index(fields=['tenant', 'store', 'product'], name='cat_inv_tnt_store_product')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'store', 'product'), name='catalog_inventory_unique_tenant_store_product')],
            },
        ),
    ]
