# Generated by Django 5.2.15 on 2026-06-25 18:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_inventorylevel'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=31)),
                ('platform_user_id', models.CharField(blank=True, max_length=127)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web', 'Web'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web', 'Web'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('external_thread_id', models.CharField(blank=True, max_length=127)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='catalog.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('external_message_id', models.CharField(blank=True, max_length=127)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='stores.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='tenants.tenant')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='catalog.messagethread')),
            ],
            options={
                'ordering': ['thread', 'sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'store', 'platform'], name='cat_cust_tnt_store_platform'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('platform_user_id__gt', '')), fields=('tenant', 'store', 'platform', 'platform_user_id'), name='catalog_customer_unique_platform_user'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['tenant', 'store', 'platform', 'status'], name='cat_thread_tnt_store_plat_stat'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['tenant', 'store', 'last_message_at'], name='cat_thread_tnt_store_last_msg'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('external_thread_id__gt', '')), fields=('tenant', 'store', 'external_thread_id'), name='catalog_thread_unique_external_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'store', 'thread', 'sent_at'], name='cat_msg_tnt_store_thread_sent'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__gt', '')), fields=('thread', 'external_message_id'), name='catalog_message_unique_external_id'),
        ),
    ]
