# Generated by Django 5.2.15 on 2026-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionevent',
            name='actor_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('system', 'System'), ('user', 'User')], max_length=16),
        ),
        migrations.AlterField(
            model_name='actionevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('queued', 'Queued')], max_length=32),
        ),
    ]
