# Generated by Django 5.2.15 on 2026-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_action_event_transition_choices'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', frozenset(['queued', 'running']))), fields=('tenant', 'store'), name='unique_active_report_run_per_store'),
        ),
    ]
