# Generated by Django 5.2.15 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_unique_active_report_run_per_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("queued", "Queued"),
                    ("executing", "Executing"),
                    ("executed", "Executed"),
                ],
                max_length=32,
            ),
        ),
    ]
