AI_SERVICE_COORDINATOR = "coordinator-agent"
AI_SERVICE_SALES = "sales-agent"
AI_SERVICE_CONTENT = "content-agent"
AI_SERVICE_SUPPORT = "support-agent"

ALLOWED_AI_SERVICES = {
    AI_SERVICE_COORDINATOR,
    AI_SERVICE_SALES,
    AI_SERVICE_CONTENT,
    AI_SERVICE_SUPPORT,
}
