from accounts.constants import (
    AI_SERVICE_CONTENT,
    AI_SERVICE_COORDINATOR,
    AI_SERVICE_SALES,
    AI_SERVICE_SUPPORT,
)

ACTION_TYPE_SALES_RESTOCK = "sales.restock"
ACTION_TYPE_SALES_DISCOUNT = "sales.discount"
ACTION_TYPE_SALES_FOLLOW_UP = "sales.follow_up"
ACTION_TYPE_CONTENT_INSTAGRAM_DRAFT = "content.instagram_draft"
ACTION_TYPE_CONTENT_PRODUCT_DESCRIPTION = "content.product_description"
ACTION_TYPE_SUPPORT_REPLY_DRAFT = "support.reply_draft"
ACTION_TYPE_SUPPORT_ESCALATE = "support.escalate"

SUPPORTED_ACTION_TYPES = frozenset(
    {
        ACTION_TYPE_SALES_RESTOCK,
        ACTION_TYPE_SALES_DISCOUNT,
        ACTION_TYPE_SALES_FOLLOW_UP,
        ACTION_TYPE_CONTENT_INSTAGRAM_DRAFT,
        ACTION_TYPE_CONTENT_PRODUCT_DESCRIPTION,
        ACTION_TYPE_SUPPORT_REPLY_DRAFT,
        ACTION_TYPE_SUPPORT_ESCALATE,
    }
)

DEFAULT_REQUIRES_APPROVAL_BY_ACTION_TYPE = {
    ACTION_TYPE_SALES_RESTOCK: True,
    ACTION_TYPE_SALES_DISCOUNT: True,
    ACTION_TYPE_SALES_FOLLOW_UP: True,
    ACTION_TYPE_CONTENT_INSTAGRAM_DRAFT: True,
    ACTION_TYPE_CONTENT_PRODUCT_DESCRIPTION: True,
    ACTION_TYPE_SUPPORT_REPLY_DRAFT: True,
    ACTION_TYPE_SUPPORT_ESCALATE: True,
}

ALLOWED_AGENT_NAMES = frozenset(
    {
        AI_SERVICE_COORDINATOR,
        AI_SERVICE_SALES,
        AI_SERVICE_CONTENT,
        AI_SERVICE_SUPPORT,
    }
)

MIN_ACTION_PRIORITY = 1
MAX_ACTION_PRIORITY = 5

ACTION_STATUS_PENDING_APPROVAL = "pending_approval"
ACTION_STATUS_QUEUED = "queued"
ACTION_STATUS_APPROVED = "approved"
ACTION_STATUS_REJECTED = "rejected"
ACTION_STATUS_CANCELLED = "cancelled"
ACTION_STATUS_EXECUTING = "executing"
ACTION_STATUS_EXECUTED = "executed"
ACTION_STATUS_FAILED = "failed"

ACTION_EVENT_TYPE_CREATED = "created"

ACTION_EVENT_ACTOR_AGENT = "agent"
ACTION_EVENT_ACTOR_SYSTEM = "system"

REPORT_RUN_STATUS_QUEUED = "queued"
REPORT_RUN_STATUS_RUNNING = "running"
REPORT_RUN_STATUS_COMPLETED = "completed"
REPORT_RUN_STATUS_FAILED = "failed"
