HISTORY_TYPE_REPORT_RUN_QUEUED = "report_run_queued"
HISTORY_TYPE_REPORT_RUN_RUNNING = "report_run_running"
HISTORY_TYPE_REPORT_RUN_COMPLETED = "report_run_completed"
HISTORY_TYPE_REPORT_RUN_FAILED = "report_run_failed"
HISTORY_TYPE_DAILY_REPORT_CREATED = "daily_report_created"
HISTORY_TYPE_AGENT_OUTPUT_CREATED = "agent_output_created"
HISTORY_TYPE_ACTION_CREATED = "action_created"
HISTORY_TYPE_ACTION_EVENT = "action_event"

HISTORY_ITEM_TYPES = frozenset(
    {
        HISTORY_TYPE_REPORT_RUN_QUEUED,
        HISTORY_TYPE_REPORT_RUN_RUNNING,
        HISTORY_TYPE_REPORT_RUN_COMPLETED,
        HISTORY_TYPE_REPORT_RUN_FAILED,
        HISTORY_TYPE_DAILY_REPORT_CREATED,
        HISTORY_TYPE_AGENT_OUTPUT_CREATED,
        HISTORY_TYPE_ACTION_CREATED,
        HISTORY_TYPE_ACTION_EVENT,
    }
)

REPORT_RUN_STATUS_TO_HISTORY_TYPE = {
    "queued": HISTORY_TYPE_REPORT_RUN_QUEUED,
    "running": HISTORY_TYPE_REPORT_RUN_RUNNING,
    "completed": HISTORY_TYPE_REPORT_RUN_COMPLETED,
    "failed": HISTORY_TYPE_REPORT_RUN_FAILED,
}

DEFAULT_HISTORY_LIMIT = 20
MAX_HISTORY_LIMIT = 100
